-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 13:02:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Original Proyecto Terminal 201208

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aiturbe_mobileHunt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aiturbe_mobileHunt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aiturbe_mobileHunt` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `aiturbe_mobileHunt` ;

-- -----------------------------------------------------
-- Table `aiturbe_mobileHunt`.`dbdesigner4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aiturbe_mobileHunt`.`dbdesigner4` ;

CREATE TABLE IF NOT EXISTS `aiturbe_mobileHunt`.`dbdesigner4` (
  `idmodel` INT(10) UNSIGNED NOT NULL,
  `idversion` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `version` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `username` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `createdate` DATETIME NULL DEFAULT NULL,
  `iscurrent` INT(1) UNSIGNED NULL DEFAULT NULL,
  `ischeckedout` INT(1) UNSIGNED NULL DEFAULT NULL,
  `info` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `model` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idmodel`, `idversion`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `aiturbe_mobileHunt`.`puntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aiturbe_mobileHunt`.`puntos` ;

CREATE TABLE IF NOT EXISTS `aiturbe_mobileHunt`.`puntos` (
  `idpuntos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarios_idUsuarios` INT(10) UNSIGNED NOT NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `provider` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`idpuntos`),
  INDEX `Posiciones_FKIndex1` (`usuarios_idUsuarios` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 4201
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `aiturbe_mobileHunt`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aiturbe_mobileHunt`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `aiturbe_mobileHunt`.`usuarios` (
  `idusuarios` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `institucion_idinstitucion` INT(10) UNSIGNED NOT NULL,
  `usuario` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `descripcion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `muestreo` INT(10) UNSIGNED NOT NULL,
  `psw_usr` INT(10) UNSIGNED NOT NULL,
  `mail` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'raymundoc.vela@hotmail.com',
  `restriccion` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `puntos_idpuntos` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `usuarios_FKIndex1` (`institucion_idinstitucion` ASC) VISIBLE,
  INDEX `fk_usuarios_puntos1` (`puntos_idpuntos` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '02Jul12 agregamos columna restriccion para guardar el javasc';


-- -----------------------------------------------------
-- Table `aiturbe_mobileHunt`.`institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aiturbe_mobileHunt`.`institucion` ;

CREATE TABLE IF NOT EXISTS `aiturbe_mobileHunt`.`institucion` (
  `idinstitucion` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usuarios_idusuarios` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idinstitucion`),
  INDEX `fk_institucion_usuarios` (`usuarios_idusuarios` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
