-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 13:08:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Modificada para acomplarse al Sitio web de Tecnologia NIMAX


-- -----------------------------------------------------
-- Table `tecnejal_mobileHunt`.`puntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnejal_mobileHunt`.`puntos` ;

CREATE TABLE IF NOT EXISTS `tecnejal_mobileHunt`.`puntos` (
  `idpuntos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarios_idUsuarios` INT(10) UNSIGNED NOT NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `provider` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`idpuntos`),
  INDEX `Posiciones_FKIndex1` (`usuarios_idUsuarios` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tecnejal_mobileHunt`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnejal_mobileHunt`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `tecnejal_mobileHunt`.`usuarios` (
  `idusuarios` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `institucion_idinstitucion` INT(10) UNSIGNED NOT NULL,
  `usuario` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `descripcion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `muestreo` INT(10) UNSIGNED NOT NULL,
  `psw_usr` INT(10) UNSIGNED NOT NULL,
  `mail` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'raymundoc.vela@hotmail.com',
  `restriccion` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `puntos_idpuntos` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `usuarios_FKIndex1` (`institucion_idinstitucion` ASC) VISIBLE,
  INDEX `fk_usuarios_puntos1` (`puntos_idpuntos` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '02Jul12 agregamos columna restriccion para guardar el javasc';


-- -----------------------------------------------------
-- Table `tecnejal_mobileHunt`.`institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tecnejal_mobileHunt`.`institucion` ;

CREATE TABLE IF NOT EXISTS `tecnejal_mobileHunt`.`institucion` (
  `idinstitucion` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usuarios_idusuarios` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idinstitucion`),
  INDEX `fk_institucion_usuarios` (`usuarios_idusuarios` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
